title: Webcam.js
description: Take pictures of yourself with your webcam and HTML5 and JavaScript and stuff
google_analytics: UA-9629600-2
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
